pipeline {
    agent {
        node {
            label 'Agent-1'
        }
    }
    environment{
        COURSE = "JENKINS"
    }
    options {
        timeout(time: 1 , unit: 'HOURS')
        disableConcurrentBuilds()
        ansiColor('xterm')
    }
    // parameters {
    //     string(name: 'PERSON', defaultValue: 'Mr Jenkins', description: 'Who should I say hello to?')
    //     text(name: 'BIOGRAPHY', defaultValue: '', description: 'Enter some information about the person')
    //     booleanParam(name: 'DEPLOY', defaultValue: false, description: 'Toggle this value')
    //     choice(name: 'CHOICE', choices: ['One', 'Two', 'Three'], description: 'Pick something')
    //     password(name: 'PASSWORD', defaultValue: 'SECRET', description: 'Enter a password')
    // }


    stages {
        stage('Init'){
            steps {
                script {
                    withAWS(region:'us-east-1',credentials:'aws-creds'){
                        sh """
                            cd 10-sg
                            terraform init
                        """
                    }
                }
            }
        }
        stage('Plan'){
            steps {
                script {
                    withAWS(region:'us-east-1',credentials:'aws-creds'){
                        sh """
                            cd 10-sg
                            terraform plan
                        """
                    }
                }
            }
        }
        stage('Apply'){
            // input {
            //     message "should we continue?"
            //     ok "Yes, we should."
            //     submitter "alice,bob"
            //     parameters{
            //         string(name: 'PRESON', defaultValue: 'MR JENKINS', describe: "who should i say hello to?")
            //     }
            // }
            steps {
                script {
                    withAWS(region:'us-east-1',credentials:'aws-creds'){
                        sh """
                            cd 10-sg
                            terraform apply -auto-approve
                        """
                    }
                }
            }
        }
        stage('Trigger SG'){
            steps {
                script {
                    build job: '10-sg',
                    wait: false
                    propagate: false
                }
            }
        }
        stage('Parallel Trigger'){
            Parallel{
                stage('Bastion'){
                    steps{
                        script{
                            build job: '20-bastion'
                            wait: false
                            propagate: false
                            
                        }
                    }
                }
                stage('SG Rules'){
                    steps{
                        script{
                            build job: '30-sg-rules'
                            wait: false
                            propagate: false
                            
                        }
                    }
                }
                stage('ECR'){
                    steps{
                        script{
                            build job: '40-ecr'
                            wait: false
                            propagate: false
                            
                        }
                    }
                }
                stage('ACM'){
                    steps{
                        script{
                            build job: '70-acm'
                            wait: true
                            propagate: false
                            
                        }
                    }
                }
                stage('EKS'){
                    steps{
                        script{
                            build job: '90-EKS'
                            wait: false
                            propagate: false
                            
                        }
                    }
                }
                stage('ALB'){
                    steps{
                        script{
                            build job: '80-frontend-alb'
                            wait: false
                            propagate: false
                            
                        }
                    }
                }
                
            }
        }

    }
    post {
        always{
            echo "I always say hello"
            cleanWs()
        }
        success{
            echo "I'm successful"
        }
        failure{
            echo "Sorry it's a failure"
        }
        aborted{
            echo "pipeline aborted"
        }
    }
}