pipeline {
    agent any

    environment {
        AWS_REGION = "us-east-1"
        REPO_URL   = "https://github.com/Rohith1845/roboshop_dev_infra.git"
    }

    stages {
        stage('Checkout') {
            steps {
                git branch: 'main',
                    credentialsId: 'github-creds',
                    url: "${REPO_URL}"
            }
        }

        stage('Approval') {
            steps {
                input message: '''⚠️ WARNING: Destroys ALL infra!
90-eks → 80-alb → 70-acm → 40-ecr → 30-sg-rules → 20-bastion → 10-sg → 00-vpc''',
                      ok: 'YES DESTROY EVERYTHING'
            }
        }

        stage('Destroy All') {
            steps {
                withAWS(region: 'us-east-1', credentials: 'aws-creds') {
                    sh '''
                        for MODULE in 90-eks 80-frontend-alb 70-acm 40-ecr 30-sg-rules 20-bastion 10-sg 00-vpc
                        do
                            echo "=========================================="
                            echo "Destroying $MODULE ..."
                            echo "=========================================="
                            cd $MODULE
                            terraform init
                            terraform destroy -auto-approve
                            cd ..
                        done
                    '''
                }
            }
        }
    }

    post {
        success {
            echo '✅ All infrastructure destroyed successfully'
        }
        failure {
            echo '❌ Destroy failed — check which module failed above in logs'
        }
    }
}
